### ISSUE TITLE
Broken with 3rd level property

### ISSUE THREAD

**Issue by RALifeCoach** [canjs/can-map-lazy#1]
I have done further analysis. It is a third level property that causes the exception. The viewModel top level properties are options, player, etc. Player has a property player_bio. player_bio has properties country, first_name, etc. When I reference, in the stache file, player.player_bio.country, I get a problem when updating the player map.attr('player', player);. If I remap the player and flatten it to player.player_bio_country, then the exception no longer happens.

**Comment by RALifeCoach** [comment]
The link to the JSBin is http://jsbin.com/qahepi/16/edit?html,js,console,output

**Comment by ramblinjan** [comment]
@RALifeCoach 
What is the point of this line?

```
map.attr('player', data.player);
```

**Comment by RALifeCoach** [comment]
Only to demonstrate that it is broken.

**Comment by ramblinjan** [comment]
@RALifeCoach 
That should be like this as you're trying to overwrite a object's properties, versus setting a single property.

```
map.attr('player').attr(data.player);
```

**Comment by RALifeCoach** [comment]
Nice!

**Comment by pYr0x** [comment]
@jandjorgensen to be clear, that behavior is only in LazyMaps? 
why is `map.attr('player', data.player);` not working? can you give us a deeper look into?

is this behavior documented?
